### ISSUE TITLE
Updating a single node

### ISSUE THREAD

**Issue by Jaq112** [pixelfac/2D-Astar-Pathfinding-in-Unity#1]
Hey,
Could you help me out update only a single cell? Currently I'm calling the Create grid to update the changes but that's not really efficient.
Thanks

**Comment by pixelfac** [comment]
so the line of code that changes the obstacle value for a certain node in a grid is:
```
Grid[x, y].SetObstacle(true);
```
So you can call SetObstacle on the Grid object in order to change just that one Node. This doesn't change the tilemap that visually represents the walkable terrain so you would have to change the tilemap tile separately with SetTile or something like that. If you are already changing the tilemap and want to update just the Grid for that tile, you would have to find the x,y positions on the grid that match that world position and the call SetObstacle on the Node at that position

**Comment by Jaq112** [comment]
Thanks for replying! 
I already updated the visuals, so I only need to update the grid now.
This is what I came up with, but I'm getting an out of bounds error.
```
  public void  UpdateGrid(Vector3Int updatedCell)
      {
          worldBottomLeft = transform.position - Vector3.right * gridWorldSize.x / 2 - Vector3.up * gridWorldSize.y / 2;
          Vector3Int worldPoint = Vector3Int.FloorToInt(worldBottomLeft + Vector3.right * (updatedCell.x * nodeDiameter + nodeRadius) + Vector3.up * (updatedCell.y * nodeDiameter - nodeRadius));
          Grid[worldPoint.x, worldPoint.y].SetObstacle(true);
      }
```

**Comment by Jaq112** [comment]
Ok, this did the trick. Had to take absolute value, also swap the operator from + to minus.
```
public void  UpdateGrid(Vector3Int updatedCell)
    {
        worldBottomLeft = transform.position - Vector3.right * gridWorldSize.x / 2 - Vector3.up * gridWorldSize.y / 2;
        print(worldBottomLeft);
        Vector3Int worldPoint = Vector3Int.FloorToInt(worldBottomLeft - (Vector3.right * (updatedCell.x)) - (Vector3.up * updatedCell.y ));
        Grid[System.Math.Abs(worldPoint.x), System.Math.Abs(worldPoint.y)].SetObstacle(true);
    }
```

I also had to change the offset for the nodeRadius in CreateGrid() from :
```
Vector3 worldPoint = worldBottomLeft + Vector3.right * (x * nodeDiameter + nodeRadius) + Vector3.up * (y * nodeDiameter + nodeRadius);
```
To:
```
Vector3 worldPoint = worldBottomLeft + Vector3.right * (x * nodeDiameter - nodeRadius) + Vector3.up * (y * nodeDiameter - nodeRadius);
```
As it was detecting the cell one to the left and down.

**Comment by pixelfac** [comment]
That's awesome to hear that you got it working! I also was having tile offset problems that I fixed somehow but it's been so long, I can't remember.
